#pragma once

enum BONEID
{
    ROOT, LHIPJOINT, LFEMUR, LTIBIA, LFOOT, LTOES, RHIPJOINT,
    RFEMUR, RTIBIA, RFOOT, RTOES, LOWERBACK, UPPERBACK, THORAX,
    LOWERNECK, UPPERNECK, HEAD, LCLAVICLE, LHUMERUS, LRADIUS,
    LWRIST, LHAND, LFINGERS, LTHUMB, RCLAVICLE, RHUMERUS, RRADIUS,
    RWRIST, RHAND, RFINGERS, RTHUMB
};

enum class DOF{
    RX, RY, RZ,
    TX, TY, TZ
};

enum class KeyInput
{
    UP, LOWERBACK, REFT, RIGHT,
    RUN, ATTACK,JUMP,STOP,CUBEFRONT,
    CUBEBACK,CUBERIGHT,CUBELEFT,
    CUBEUP, CUBEDOWN
};

enum BlendNode // index 접근할지 순회 돌지 고민
{
    BASE, UPPER, LOWER
};

enum class PlayerState
{
    IDLE, RUN, WALK
};